import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "OpenTable",
    template: "OpenTable %s",
  },
  description: "Generated by create next app",
};

// const getRepo = async () => {
//   const response = await fetch(
//     "https://api.github.com/repos/gxanshu/codenanshu"
//   );
//   return await response.json();
// };

// const getTime = async () => {
//   const response = await fetch(
//     "http://worldtimeapi.org/api/timezone/Asia/kolkata",
//     {
//       next: {
//         revalidate: 5,
//       },
//     }
//   );

//   return response.json()
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const [repo,time] = await Promise.all([getRepo(),getTime()]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-gray-100 min-h-screen w-screen">
          <main className="max-w-screen-2xl m-auto bg-white">
            <Navbar />
            {/* <p>{repo.full_name}</p>
            <p>{time.datetime}</p> */}
            {children}
          </main>
        </main>
      </body>
    </html>
  );
}
