import { Metadata } from "next";
import Navbar from "../components/Navbar";
import Header from "./components/Header";
import RestaurantCard from "./components/RestaurantCard";
import Sidebar from "./components/Sidebar";
import { PRICE, PrismaClient, Region } from "@prisma/client";

const prisma = new PrismaClient();

export const metadata: Metadata = {
  title: " Search ",
  description: "Generated by create next app",
  keywords: "nextjs,restaurant,search",
};

const searchRestaurnats = (city: string | undefined) => {
  const select = {
    id: true,
    name: true,
    main_image: true,
    price: true,
    location: true,
    region: true,
    slug: true,
  };
  if (!city) return prisma.restaurant.findMany({ select });
  return prisma.restaurant.findMany({
    where: {
      location: {
        name: {
          equals: city.toLowerCase(),
        },
      },
    },
    select,
  });
};

const fetchLocations = () => {
  return prisma.location.findMany();
};
const fetchRegions = () => {
  return prisma.region.findMany();
};

async function searchPage({
  searchParams,
}: {
  searchParams: { city?: string; region?: Region; price?: PRICE };
}) {
  const restaurnats = await searchRestaurnats(searchParams.city);
  const locations = await fetchLocations();
  const regions = await fetchRegions();

  return (
    <>
      <Header />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <Sidebar searchParams={searchParams} 
        locations={locations} regions={regions} />

        <div className="w-5/6">
          {restaurnats.length
            ? restaurnats.map((restaurnat) => (
                <RestaurantCard restaurant={restaurnat} />
              ))
            : "Sory no restaurnats found"}
        </div>
      </div>
    </>
  );
}

export default searchPage;
